In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [3]:
# 역행렬
A_tranpose = np.transpose(A)

A_tranpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [4]:
# T 는 열과 행을 바꾸어주는 매서드
A_tranpose = A.T

A_tranpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [5]:
# 단위 행렬 만들기 identity(a) axa 의 단위 행렬 생성
I = np.identity(3)

I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [8]:
# 역행렬 구하기
# numpy의 linalg 모듈의 pinv 메서드 사용
A_inverse = np.linalg.pinv(A)

A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [9]:
# 역행렬이 맞는지 확인해보기
# -16승 이라는 것은 0에 엄청 가까운 수
# 컴퓨터가 소수 0을 다룰 때 약간의 오차가 생기기 때문
A @ A_inverse

array([[ 1.00000000e+00,  5.55111512e-16, -8.88178420e-16],
       [ 2.22044605e-16,  1.00000000e+00, -8.88178420e-16],
       [ 2.22044605e-16,  2.22044605e-16,  1.00000000e+00]])