In [1]:
import numpy as np

In [4]:
# 행렬을 만들고 싶을 때에는 2차원 배열을 사용
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

In [5]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [6]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])

B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [7]:
C = np.random.rand(3, 5)

C

array([[0.83747939, 0.49363692, 0.15122565, 0.28843046, 0.85218951],
       [0.18547992, 0.00318138, 0.80988612, 0.66425806, 0.46503043],
       [0.03783692, 0.45553516, 0.4700907 , 0.48895604, 0.32324041]])

In [9]:
# zeros 메서드는 행렬을 만들때 괄호를 한번 더 써주어야 함
D = np.zeros((2, 4))

D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [11]:
A[0][2]

2