In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

In [3]:
B = np.random.rand(3, 3)

In [4]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [5]:
B

array([[0.2069454 , 0.62127249, 0.08117147],
       [0.86707869, 0.3714284 , 0.11216519],
       [0.85099437, 0.76291224, 0.03078359]])

In [6]:
A + B

array([[ 1.2069454 , -0.37872751,  2.08117147],
       [ 3.86707869,  2.3714284 ,  2.11216519],
       [ 4.85099437,  1.76291224,  2.03078359]])

In [7]:
# 스칼라곱
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [8]:
# 행렬과 행렬의 곱
np.dot(A, B)

array([[1.04185546, 1.77566856, 0.03057345],
       [4.05698233, 4.13249875, 0.52941198],
       [3.39684905, 4.38234283, 0.49841825]])

In [9]:
# dot() 메서드와 @ 연산자는 같다
A @ B

array([[1.04185546, 1.77566856, 0.03057345],
       [4.05698233, 4.13249875, 0.52941198],
       [3.39684905, 4.38234283, 0.49841825]])

In [10]:
A @ B + (A + 2 * B)

array([[2.45574627, 2.01821353, 2.19291639],
       [8.7911397 , 6.87535555, 2.75374237],
       [9.09883779, 6.90816731, 2.55998543]])